from .animal import AnimalViewSet
from .categoria_registro import CategoriaRegistroViewSet
from .desmame import DesmameViewSet
from .identificador import IdentificadorViewSet
from .lote import LoteViewSet
from .nascimento import NascimentoViewSet
from .pelagem import PelagemViewSet
from .organizacao import OrganizacaoViewSet
from .raca import RacaViewSet
from .subdivisao import SubdivisaoViewSet
from .vaca_lote import VacaLoteViewSet