# Generated by Django 5.0.2 on 2024-02-27 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id_animal', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('data_nascimento', models.DateField(default='31/12/2000')),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1)),
                ('animal_ativo', models.BooleanField(default=True)),
                ('atividade', models.CharField(choices=[('C', 'Cria'), ('R', 'Recria'), ('E', 'Engorda')], default='C', max_length=1)),
                ('categoria', models.CharField(choices=[('BE', 'Bezerro'), ('GA', 'Garrote'), ('TO', 'Touro'), ('BI', 'Boi'), ('BA', 'Bezerra'), ('NO', 'Novilha'), ('VA', 'Vaca')], default='BE', max_length=2)),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
            },
        ),
        migrations.CreateModel(
            name='Pelagem',
            fields=[
                ('id_pelagem', models.AutoField(primary_key=True, serialize=False)),
                ('nome_pelagem', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Pelagem',
                'verbose_name_plural': 'Pelagens',
            },
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id_raca', models.AutoField(primary_key=True, serialize=False)),
                ('nome_raca', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Raça',
                'verbose_name_plural': 'Raças',
            },
        ),
        migrations.CreateModel(
            name='Nascimento',
            fields=[
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='animal_nascimento', serialize=False, to='core.animal')),
                ('tamanho_nascimento', models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande')], default='M', max_length=1)),
                ('data_nascimento', models.DateField(default='31/12/2000')),
                ('situacao_nascimento', models.CharField(choices=[('U', 'Único'), ('M', 'Múltiplo'), ('D', 'Defeituoso Único'), ('N', 'Defeituoso Múltiplo')], default='U', max_length=1)),
                ('ordem_parto', models.IntegerField(default=1, null=True)),
                ('tipo_parto', models.CharField(choices=[('N', 'Normal'), ('A', 'Assistido'), ('C', 'Cirúrguco'), ('M', 'Natimorto'), ('F', 'Abortado')], default='N', max_length=1)),
            ],
            options={
                'verbose_name': 'Nascimento',
                'verbose_name_plural': 'Nascimentos',
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='pelagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pelagem_animal', to='core.pelagem'),
        ),
        migrations.AddField(
            model_name='animal',
            name='raca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raca_animal', to='core.raca'),
        ),
    ]
