# Generated by Django 5.0.2 on 2024-03-07 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaRegistro',
            fields=[
                ('id_categoria_registro', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Categoria de Registro',
                'verbose_name_plural': 'Categorias de Registro',
            },
        ),
        migrations.CreateModel(
            name='Organizacao',
            fields=[
                ('id_organizacao', models.AutoField(primary_key=True, serialize=False)),
                ('nome_organizacao', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('cnpj', models.CharField(max_length=20)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('data_atualizacao', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organização',
                'verbose_name_plural': 'Organizações',
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='numero_animal',
            field=models.CharField(default='0000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_ativo',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='atividade',
            field=models.CharField(choices=[('C', 'Cria'), ('R', 'Recria'), ('E', 'Engorda')], default='C', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='categoria',
            field=models.CharField(choices=[('BE', 'Bezerro'), ('GA', 'Garrote'), ('TO', 'Touro'), ('BI', 'Boi'), ('BA', 'Bezerra'), ('NO', 'Novilha'), ('VA', 'Vaca')], default='BE', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='data_nascimento',
            field=models.DateField(default='2000-12-31', null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='id_animal',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='animal',
            name='pelagem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pelagem_animal', to='core.pelagem'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='raca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raca_animal', to='core.raca'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='Subdivisao',
            fields=[
                ('id_subdivisao', models.AutoField(primary_key=True, serialize=False)),
                ('nome_subdivisao', models.CharField(max_length=100)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('data_atualizacao', models.DateField(auto_now=True)),
                ('organizacao', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organizacao_subdivisao', to='core.organizacao')),
            ],
            options={
                'verbose_name': 'Subdivisão',
                'verbose_name_plural': 'Subdivisões',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id_lote', models.AutoField(primary_key=True, serialize=False)),
                ('nome_lote', models.CharField(max_length=100)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('data_atualizacao', models.DateField(auto_now=True)),
                ('touro', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='touro_lote', to='core.animal')),
                ('vaca', models.ManyToManyField(related_name='vaca_lote', to='core.animal')),
                ('organizacao', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subdivisao_lote', to='core.subdivisao')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
            },
        ),
    ]
