# Generated by Django 5.0.2 on 2024-02-27 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lote_organizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='organizacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organizacao_lote', to='core.organizacao'),
        ),
    ]
