# Generated by Django 5.0.2 on 2024-03-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoriaregistro_organizacao_animal_numero_animal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_ativo',
            field=models.BooleanField(default=True),
        ),
    ]
