# Generated by Django 5.0.2 on 2024-03-07 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_animal_animal_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desmame',
            fields=[
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='animal_desmame', serialize=False, to='core.animal')),
                ('data_desmame', models.DateField(default='31/12/2000')),
                ('peso_desmame', models.FloatField(default=1, null=True)),
            ],
            options={
                'verbose_name': 'Desmame',
                'verbose_name_plural': 'Desmames',
            },
        ),
        migrations.RemoveField(
            model_name='animal',
            name='data_nascimento',
        ),
        migrations.AlterField(
            model_name='nascimento',
            name='data_nascimento',
            field=models.DateField(default='2000-12-31', null=True),
        ),
    ]
