# Generated by Django 5.0.2 on 2024-02-27 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lote_organizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='lote',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lote_animal', to='core.lote'),
        ),
    ]
