# Generated by Django 5.0.2 on 2024-03-07 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_desmame_remove_animal_data_nascimento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identificador',
            fields=[
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='animal_identificador', serialize=False, to='core.animal')),
                ('nome_animal', models.CharField(max_length=100, null=True)),
                ('brinco_eletronico', models.CharField(max_length=50, null=True)),
                ('numero_sisbov', models.CharField(max_length=50, null=True)),
                ('data_id_sisbov', models.DateField(null=True)),
                ('data_certificacao_sisbov', models.DateField(null=True)),
                ('registro_nascimento', models.CharField(max_length=50, null=True)),
                ('registro_definitivo', models.CharField(max_length=50, null=True)),
                ('serie', models.CharField(max_length=50, null=True)),
                ('a12', models.CharField(max_length=50, null=True)),
                ('serie_paint_cia', models.CharField(max_length=50, null=True)),
                ('categoria_registro', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='categoria_registro_identificador', to='core.categoriaregistro')),
            ],
            options={
                'verbose_name': 'Identificador',
                'verbose_name_plural': 'Identificadores',
            },
        ),
    ]
