# Generated by Django 5.0.2 on 2024-03-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_identificador'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='chifre',
            field=models.CharField(choices=[('CA', 'Calo'), ('AS', 'Aspa'), ('BT', 'Batoque'), ('BA', 'Bananinha')], default='CA', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='padrao',
            field=models.CharField(choices=[('AN', 'Anerolado'), ('CI', 'Cruzamento Industrial'), ('CL', 'Cruzamento Leiteiro'), ('ZE', 'Zebuíno')], default='AN', max_length=2, null=True),
        ),
    ]
