# Generated by Django 5.0.2 on 2024-03-04 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_animal_data_nascimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizacao',
            old_name='nome',
            new_name='nome_organizacao',
        ),
    ]
