# Generated by Django 5.0.2 on 2024-03-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_animal_chifre_animal_padrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categoriaregistro',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='desmame',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='identificador',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nascimento',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pelagem',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='raca',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subdivisao',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
