# Generated by Django 5.0.2 on 2024-03-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_nome_organizacao_nome_organizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaRegistro',
            fields=[
                ('id_categoria_registro', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Categoria de Registro',
                'verbose_name_plural': 'Categorias de Registro',
            },
        ),
    ]
