# Generated by Django 5.0.2 on 2024-03-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_lote_vaca_vacalote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacalote',
            name='data_atualizacao',
        ),
        migrations.RemoveField(
            model_name='vacalote',
            name='data_cadastro',
        ),
        migrations.AddField(
            model_name='vacalote',
            name='conf',
            field=models.FloatField(default=0.0),
        ),
    ]
