# Generated by Django 5.0.2 on 2024-03-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_vacalote_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desmame',
            name='data_desmame',
            field=models.DateField(default='2021-01-20'),
        ),
    ]
