# Generated by Django 5.0.2 on 2024-03-07 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_desmame_data_desmame'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vacalote',
            unique_together={('lote', 'vaca')},
        ),
    ]
