from .animal import AnimalSerializer
from .categoria_registro import CategoriaRegistroSerializer
from .desmame import DesmameSerializer
from .identificador import IdentificadorSerializer
from .lote import LoteSerializer
from .nascimento import NascimentoSerializer
from .pelagem import PelagemSerializer
from .organizacao import OrganizacaoSerializer
from .raca import RacaSerializer
from .subdivisao import SubdivisaoSerializer
from .vaca_lote import VacaLoteSerializer