from .animal import Animal
from .categoria_registro import CategoriaRegistro
from .desmame import Desmame
from .identificador import Identificador
from .lote import Lote
from .nascimento import Nascimento
from .organizacao import Organizacao
from .pelagem import Pelagem
from .raca import Raca
from .subdivisao import Subdivisao
from .vaca_lote import VacaLote